from . import hr_contract
from . import hr_employee
from . import res_config_settings
from . import hr_salary_rule
from . import hr_payslip
from . import advence_loan_payroll
from . import journal_paie
from . import ordre_virement
from . import declaration_cnss
from . import etat_annuelle_employee
