{
    'name': "NN Paie",
    'author': 'NN Tech',
    'category': 'Human Resources',
    'summary': "Module de gestion de la paie pour NN Technologies",
    'license': 'AGPL-3',
    'website': 'https://www.bmgtech.tn',
    'description': "Modules NN Technologies Paie",
    'version': '17.0.1.0',
    'depends': [
        'nn_admin',
        'hr_contract',
        'base',
        'hr_holidays',
        'nn_hr',
        'nn_hr_tn',
        'nn_advance',
        'nn_loan',
        'report_xlsx',

    ],
    'data': [
        'security/hr_payroll_security.xml',
        'security/ir.model.access.csv',
        'data/hr_payroll_sequence.xml',
        'data/hr_payroll_category.xml',
        'data/hr_payroll_data.xml',
        'data/sequences.xml',
        'report/analyse_reports.xml',
        'report/journal_paie_pdf_report.xml',
        'report/ordre_virement_pdf_report.xml',
        'report/declaration_cnss_report.xml',
        'report/etat_annuelle_employee_report.xml',
        'report/etat_annuelle_employee_specific_report.xml',
        'report/lots_bulletins_paie_report.xml',
        'report/declaration_cnss_etat_recapitulatif.xml',
        'views/report_payslip_templates.xml',
        'views/report_payslip_details_templates.xml',
        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'wizard/employee_certificate_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_salary_rule_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_payroll_report.xml',
        'wizard/hr_payroll_contribution_register_report_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_contribution_register_templates.xml',

        'views/journal_paie_and_line_view.xml',
        'views/declaration_cnss_form_tree_views.xml',
        'views/ordre_virement_form_tree_view.xml',
        'views/company_views.xml',
        'views/etat_annuelle_employee_form_tree.xml',
        'views/advance.xml',
        'views/loan.xml',
        'views/etat_avance_mensuelles.xml',
        'views/etat_pret_mensuel.xml',
        # 'views/assets.xml',

        # 'data/mail_template.xml',

    ],
    'assets': {
        'web.assets_backend': [
            # 'nn_paie/static/src/js/hide_new_button.js',
            'nn_paie/static/src/css/hide_new_button.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
